= BarbaryWatchService

This is the official BarbaryWatchService repository, moved from https://code.google.com/p/barbarywatchservice/

See link:issues/[issues] for current plans.

image:https://travis-ci.org/gjoseph/BarbaryWatchService.svg?branch=master["Build Status", link="https://travis-ci.org/gjoseph/BarbaryWatchService"]

= An implementation of Java 7's WatchService for Java 6 on Mac OS X

Java 7 has an API to detect file system changes called Watch Service. This project uses JNA to hook into Apple's File System Events API.

This is almost a direct drop-in replacement for Java 7's Watch Service API. I've used the API source code from OpenJDK 7 as much as possible.

There's a link:Demo.asciidoc[Demo example here].

A lot of source code is from OpenJDK.

== Differences from Java 7's API
You obtain a Watch Service instance as follows:

[source,java]
WatchService watcher = WatchService.newWatchService();

Instead of creating Path objects, use `WatchableFile` objects:
[source,java]
WatchableFile file1 = new WatchableFile(new File("/path/to/watch"));

http://openjdk.java.net/projects/nio/javadoc/java/nio/file/WatchService.html[Read the JavaDocs for Java 7's Watch Service API].

There is a tutorial for https://docs.oracle.com/javase/tutorial/essential/io/notification.html[Java 7's Watch Service API here].

= Download

Get the Maven dependency:

[source,xml]
----
  <dependency>
    <groupId>net.incongru.watchservice</groupId>
    <artifactId>barbary-watchservice</artifactId>
    <version>1.0</version>
  </dependency>
----

